apiVersion: v1
kind: Pod
metadata:
  name: sa-frontend2
  labels:
    app: sa-frontend
spec:
  containers:
    - image: kwizatshaderah1/sa-frontend:ubuntuTest 
      name: sa-frontend
      ports:
        - containerPort: 80
